version: '3.8'
services:

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.4.13
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181

  kafka:
    container_name: kafka
    image: bitnami/kafka:2.8.1
    restart: always
    ports:
      - 9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:39092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper

  zookeeper2:
    container_name: zookeeper2
    image: bitnami/zookeeper:3.4.13
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181

  kafka2:
    container_name: kafka2
    image: bitnami/kafka:2.8.1
    restart: always
    ports:
      - 9092
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:39092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    depends_on:
      - zookeeper2

  mirrormaker:
    container_name: mirrormaker
    image: '0qqw/kafka-mirror-maker:2.8.1'
    depends_on:
      - kafka
      - kafka2
    environment:
      SOURCE: kafka2:9092
      DESTINATION: kafka:9092
      KAFKA_CFG_LISTENERS: ""
      ALLOW_PLAINTEXT_LISTENER: "yes"
